name: Update README ⭐
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Udate README
        uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2403535
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2022
      
      - name: Raise PR
        id: readme
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-readme-pr"
          base: main
          title: "Auto update Readme ⭐"
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          
      - name: Approve PR
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.readme.outputs.pull-request-number }}
          
      - name: Merge PR
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.readme.outputs.pull-request-number }}
          method: squash
