name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

  day1:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day01 --verbose
  day2:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day02 --verbose
  day3:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day03 --verbose
  day4:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day04 --verbose
  day5:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day05 --verbose
  day6:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day06 --verbose
  day7:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day07 --verbose
  day8:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day08 --verbose
  day9:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day09 --verbose
  day10:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day10 --verbose
  day11:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day11 --verbose
  day12:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day12 --verbose
  day13:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day13 --verbose
  day14:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day14 --verbose
  day15:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day15 --verbose
  day16:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day16 --verbose
  day17:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day17 --verbose
  day18:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day18 --verbose
  day19:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day19 --verbose
  day20:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day20 --verbose
  day21:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day21 --verbose
  day22:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day22 --verbose
  day23:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day23 --verbose
  day24:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day24 --verbose
  day25:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: cargo test -p day25 --verbose
